name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [build, lint, test]
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: 16
        check-latest: true

    - run: npm ci
    - run: npm run ${{ matrix.job }}
